version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: receiptocr
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/receiptocr
      # Add other environment variables as needed
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./web
    command: npm run dev
    ports:
      - '5173:5173'
    volumes:
      - ./web:/app
    working_dir: /app
    depends_on:
      - backend

volumes:
  db_data:
